{
 "title": "Sensor monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Potential invalid measures",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "measurement": "sensor.generated_metrics_number",
     "query": "SELECT count(\"value\") FROM \"sensor.concurrent_players\" WHERE (\"is_valid_preprocess\" = 'False') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "Errors occuring while gathring sensor metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bounded random generator parsing failure",
     "measurement": "sensor.error.sensor.bounded_random_generator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Cpu load parsing failure",
     "measurement": "sensor.error.sensor.cpu_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Generated metrics number parsing  error",
     "measurement": "sensor.error.sensor.generated_metrics_number",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "influxdb metric storing error",
     "measurement": "sensor.error.batch_sending_error",
     "query": "SELECT \"value\" FROM \"sensor.error.batch_sending_error\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sensor.error.batch_sending_error",
     "query": "SELECT count(\"value\") FROM \"sensor.error.batch_sending_error\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Connectivity error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"sensor.error.connectivity_error\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts status", "type": "alertlist", "gridPos": { "h": 16, "w": 4, "x": 16, "y": 0 } },
  {
   "title": "Random generator values distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of occurence of a number in the value range corresponding"
    }
   ],
   "targets": [
    {
     "alias": "Random value",
     "measurement": "sensor.bounded_random_generator",
     "query": "SELECT \"value\" FROM \"sensor.bounded_random_generator\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Number of distinct values of the random generator",
   "type": "singlestat",
   "description": "Note that the more potential wrong values are happening, the less values would appear here. This does not mean that the random generator is wrong though, rely on alarms for that",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  count(distinct(\"value\"))  FROM \"sensor.bounded_random_generator\" WHERE $timeFilter AND (\"is_valid_preprocess\" = 'True')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Random generator values evolution",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Random generated value",
     "measurement": "sensor.bounded_random_generator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Standard deviation last 10s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT stddev(\"value\") FROM \"sensor.bounded_random_generator\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Spread last 10s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"sensor.bounded_random_generator\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current counter value",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sensor.generated_metrics_number",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Counter non negative difference",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Difference with previous value",
     "measurement": "sensor.count_user_login",
     "query": "SELECT difference(\"value\") FROM \"sensor.generated_metrics_number\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Cpu load last second (8 cores)",
   "type": "graph",
   "description": "This graph ocntains metrics",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Current cpu load average on the last second",
     "measurement": "sensor.cpu_load",
     "query": "SELECT \"value\" FROM \"sensor.cpu_load\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Spread of the values in the last 20s",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor.cpu_load",
     "query": "SELECT spread(\"value\") FROM \"sensor.cpu_load\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ],
     "tags": [
      { "key": "is_valid_preprocess", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Count of the max values of each 10s interval over 60s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(max_value) FROM (SELECT max(\"value\") as max_value FROM \"sensor.cpu_load\" WHERE (\"is_valid_preprocess\" = 'True') AND $timeFilter GROUP BY  time(10s)) WHERE $timeFilter  AND max_value>16 GROUP BY time(60s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}